In [249]:
import pandas as pd
import seaborn as sns
import numpy as np

In [250]:
movie=pd.read_csv('Movie_collection.csv')
movie

Collection  Marketing expense  Production expense  Multiplex coverage  \
0         48000            20.1264               59.62               0.462   
1         43200            20.5462               69.14               0.531   
2         69400            20.5458               69.14               0.531   
3         66800            20.6474               59.36               0.542   
4         72400            21.3810               59.36               0.542   
..          ...                ...                 ...                 ...   
501       44800            21.2526               78.86               0.427   
502       41200            20.9054               78.86               0.427   
503       47800            21.2152               78.86               0.427   
504       44000            22.1918               78.86               0.427   
505       38000            20.9482               78.86               0.427   

        Budget  Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  \
0    36524.125         138.7               7.825                8.095   
1    35668.655         152.4               7.505                7.650   
2    39912.675         134.6               7.485                7.570   
3    38873.890         119.3               6.895                7.035   
4    39701.585         127.7               6.920                7.070   
..         ...           ...                 ...                  ...   
501  36624.115         142.6               8.680                8.775   
502  33996.600         150.2               8.780                8.945   
503  38751.680         164.5               8.830                8.970   
504  37740.670         162.8               8.730                8.845   
505  33496.650         154.3               8.640                8.880   

     Director_rating  Producer_rating  Critic_rating  Trailer_views  \
0              7.910            7.995           7.94         527367   
1              7.440            7.470           7.44         494055   
2              7.495            7.515           7.44         547051   
3              6.920            7.020           8.26         516279   
4              6.815            7.070           8.26         531448   
..               ...              ...            ...            ...   
501            8.620            8.970           6.80         492480   
502            8.770            8.930           7.80         482875   
503            8.855            9.010           7.80         532239   
504            8.800            8.845           6.80         496077   
505            8.680            8.790           6.80         518438   

    3D_available  Time_taken  Twitter_hastags     Genre  Avg_age_actors  \
0            YES      109.60          223.840  Thriller              23   
1             NO      146.64          243.456     Drama              42   
2             NO      147.88         2022.400    Comedy              38   
3            YES      185.36          225.344     Drama              45   
4             NO      176.48          225.792     Drama              55   
..           ...         ...              ...       ...             ...   
501           NO      186.96          243.584    Action              27   
502          YES      132.24          263.296    Action              20   
503           NO      109.56          243.824    Comedy              31   
504          YES      158.80          303.520    Comedy              47   
505          YES      205.60          203.040    Comedy              45   

    MPAA_film_rating  Num_multiplex  Start_Tech_Oscar  
0                 PG            494                 0  
1                 PG            462                 1  
2                 PG            458                 0  
3                 PG            472                 0  
4                 PG            395                 0  
..               ...            ...               ...  
501               PG            561          

In [251]:
movie.describe()

Collection  Marketing expense  Production expense  \
count     506.000000         506.000000          506.000000   
mean    45057.707510          92.270471           77.273557   
std     18364.351764         172.030902           13.720706   
min     10000.000000          20.126400           55.920000   
25%     34050.000000          21.640900           65.380000   
50%     42400.000000          25.130200           74.380000   
75%     50000.000000          93.541650           91.200000   
max    100000.000000        1799.524000          110.480000   

       Multiplex coverage        Budget  Movie_length  Lead_ Actor_Rating  \
count          506.000000    506.000000    506.000000          506.000000   
mean             0.445305  34911.144022    142.074901            8.014002   
std              0.115878   3903.038232     28.148861            1.054266   
min              0.129000  19781.355000     76.400000            3.840000   
25%              0.376000  32693.952500    118.525000            7.316250   
50%              0.462000  34488.217500    151.000000            8.307500   
75%              0.551000  36793.542500    167.575000            8.865000   
max              0.615000  48772.900000    173.500000            9.435000   

       Lead_Actress_rating  Director_rating  Producer_rating  Critic_rating  \
count           506.000000       506.000000       506.000000     506.000000   
mean              8.185613         8.019664         8.190514       7.810870   
std               1.054290         1.059899         1.049601       0.659699   
min               4.035000         3.840000         4.030000       6.600000   
25%               7.503750         7.296250         7.507500       7.200000   
50%               8.495000         8.312500         8.465000       7.960000   
75%               9.030000         8.883750         9.030000       8.260000   
max               9.540000         9.425000         9.635000       9.400000   

       Trailer_views  Time_taken  Twitter_hastags  Avg_age_actors  \
count     506.000000  494.000000       506.000000      506.000000   
mean   449860.715415  157.391498       260.832095       39.181818   
std     68917.763145   31.295161       104.779133       12.513697   
min    212912.000000    0.000000       201.152000        3.000000   
25%    409128.000000  132.300000       223.796000       28.000000   
50%    462460.000000  160.000000       254.400000       39.000000   
75%    500247.500000  181.890000       283.416000       50.000000   
max    567784.000000  217.520000      2022.400000       60.000000   

       Num_multiplex  Start_Tech_Oscar  
count     506.000000        506.000000  
mean      545.043478          0.454545  
std       106.332889          0.498422  
min       333.000000          0.000000  
25%       465.000000          0.000000  
50%       535.500000          0.000000  
75%       614.750000          1.000000  
max       868.000000          1.000000

In [252]:
np.percentile(movie.Twitter_hastags,[99][0])

307.9904

In [253]:
uv=np.percentile(movie.Twitter_hastags,[99][0])

In [254]:
uv

307.9904

In [255]:
movie.Twitter_hastags[(movie.Twitter_hastags > 3*uv)] =3*uv

C:\Users\akhil\miniconda3\envs\jupyter\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [256]:
movie.describe()

Collection  Marketing expense  Production expense  \
count     506.000000         506.000000          506.000000   
mean    45057.707510          92.270471           77.273557   
std     18364.351764         172.030902           13.720706   
min     10000.000000          20.126400           55.920000   
25%     34050.000000          21.640900           65.380000   
50%     42400.000000          25.130200           74.380000   
75%     50000.000000          93.541650           91.200000   
max    100000.000000        1799.524000          110.480000   

       Multiplex coverage        Budget  Movie_length  Lead_ Actor_Rating  \
count          506.000000    506.000000    506.000000          506.000000   
mean             0.445305  34911.144022    142.074901            8.014002   
std              0.115878   3903.038232     28.148861            1.054266   
min              0.129000  19781.355000     76.400000            3.840000   
25%              0.376000  32693.952500    118.525000            7.316250   
50%              0.462000  34488.217500    151.000000            8.307500   
75%              0.551000  36793.542500    167.575000            8.865000   
max              0.615000  48772.900000    173.500000            9.435000   

       Lead_Actress_rating  Director_rating  Producer_rating  Critic_rating  \
count           506.000000       506.000000       506.000000     506.000000   
mean              8.185613         8.019664         8.190514       7.810870   
std               1.054290         1.059899         1.049601       0.659699   
min               4.035000         3.840000         4.030000       6.600000   
25%               7.503750         7.296250         7.507500       7.200000   
50%               8.495000         8.312500         8.465000       7.960000   
75%               9.030000         8.883750         9.030000       8.260000   
max               9.540000         9.425000         9.635000       9.400000   

       Trailer_views  Time_taken  Twitter_hastags  Avg_age_actors  \
count     506.000000  494.000000       506.000000      506.000000   
mean   449860.715415  157.391498       257.280993       39.181818   
std     68917.763145   31.295161        53.775554       12.513697   
min    212912.000000    0.000000       201.152000        3.000000   
25%    409128.000000  132.300000       223.796000       28.000000   
50%    462460.000000  160.000000       254.400000       39.000000   
75%    500247.500000  181.890000       283.416000       50.000000   
max    567784.000000  217.520000       923.971200       60.000000   

       Num_multiplex  Start_Tech_Oscar  
count     506.000000        506.000000  
mean      545.043478          0.454545  
std       106.332889          0.498422  
min       333.000000          0.000000  
25%       465.000000          0.000000  
50%       535.500000          0.000000  
75%       614.750000          1.000000  
max       868.000000          1.000000

In [257]:
mov=pd.get_dummies(movie)

In [258]:
mov.head(10)

Collection  Marketing expense  Production expense  Multiplex coverage  \
0       48000            20.1264               59.62               0.462   
1       43200            20.5462               69.14               0.531   
2       69400            20.5458               69.14               0.531   
3       66800            20.6474               59.36               0.542   
4       72400            21.3810               59.36               0.542   
5       57400            20.5970               59.36               0.542   
6       45800            21.7658               70.74               0.476   
7       44200            22.8910               70.74               0.476   
8       33000            24.2248               70.74               0.476   
9       37800            23.4008               70.74               0.476   

      Budget  Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  \
0  36524.125         138.7               7.825                8.095   
1  35668.655         152.4               7.505                7.650   
2  39912.675         134.6               7.485                7.570   
3  38873.890         119.3               6.895                7.035   
4  39701.585         127.7               6.920                7.070   
5  35718.650         132.2               6.890                7.100   
6  33396.660         140.1               7.065                7.265   
7  34285.460         169.6               6.980                7.075   
8  31280.205         173.5               6.910                7.075   
9  33352.220         159.4               6.665                6.725   

   Director_rating  Producer_rating  ...  Avg_age_actors  Num_multiplex  \
0            7.910            7.995  ...              23            494   
1            7.440            7.470  ...              42            462   
2            7.495            7.515  ...              38            458   
3            6.920            7.020  ...              45            472   
4            6.815            7.070  ...              55            395   
5            6.885            7.005  ...              53            460   
6            7.150            7.400  ...              41            522   
7            6.875            7.170  ...              56            571   
8            6.850            7.000  ...              55            564   
9            6.575            6.855  ...              45            508   

   Start_Tech_Oscar  3D_available_NO  3D_available_YES  Genre_Action  \
0                 0                0                 1             0   
1                 1                1                 0             0   
2                 0                1                 0             0   
3                 0                0                 1             0   
4                 0                1                 0             0   
5                 1                0                 1             0   
6                 1                0                 1             0   
7                 1                1                 0             0   
8                 0                0                 1             0   
9                 0                0                 1             0   

   Genre_Comedy  Genre_Drama  Genre_Thriller  MPAA_film_rating_PG  
0             0            0               1                    1  
1             0            1               0                    1  
2             1            0               0                    1  
3             0            1               0                    1  
4             0            1               0                    1  
5             1            0               0                    1  
6             0            0               1                    1  
7             0            1               0                    1  
8             1            0               0                    1  
9             0            0               1                    1  

[10 rows x 24 co

In [259]:
del mov['3D_available_NO']

In [260]:
mov.head()

Collection  Marketing expense  Production expense  Multiplex coverage  \
0       48000            20.1264               59.62               0.462   
1       43200            20.5462               69.14               0.531   
2       69400            20.5458               69.14               0.531   
3       66800            20.6474               59.36               0.542   
4       72400            21.3810               59.36               0.542   

      Budget  Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  \
0  36524.125         138.7               7.825                8.095   
1  35668.655         152.4               7.505                7.650   
2  39912.675         134.6               7.485                7.570   
3  38873.890         119.3               6.895                7.035   
4  39701.585         127.7               6.920                7.070   

   Director_rating  Producer_rating  ...  Twitter_hastags  Avg_age_actors  \
0            7.910            7.995  ...         223.8400              23   
1            7.440            7.470  ...         243.4560              42   
2            7.495            7.515  ...         923.9712              38   
3            6.920            7.020  ...         225.3440              45   
4            6.815            7.070  ...         225.7920              55   

   Num_multiplex  Start_Tech_Oscar  3D_available_YES  Genre_Action  \
0            494                 0                 1             0   
1            462                 1                 0             0   
2            458                 0                 0             0   
3            472                 0                 1             0   
4            395                 0                 0             0   

   Genre_Comedy  Genre_Drama  Genre_Thriller  MPAA_film_rating_PG  
0             0            0               1                    1  
1             0            1               0                    1  
2             1            0               0                    1  
3             0            1               0                    1  
4             0            1               0                    1  

[5 rows x 23 columns]

In [261]:
from sklearn.linear_model import LogisticRegression


In [262]:
X=mov[['Budget','Multiplex coverage','Production expense','Marketing expense','Collection','Movie_length','Lead_ Actor_Rating',
        'Lead_Actress_rating','Director_rating','Producer_rating','Twitter_hastags','Avg_age_actors','Num_multiplex','3D_available_YES',
        'Genre_Action','Genre_Comedy','Genre_Thriller','Genre_Drama','MPAA_film_rating_PG']]

In [263]:
y=mov['Start_Tech_Oscar']

In [264]:
X.head()

Budget  Multiplex coverage  Production expense  Marketing expense  \
0  36524.125               0.462               59.62            20.1264   
1  35668.655               0.531               69.14            20.5462   
2  39912.675               0.531               69.14            20.5458   
3  38873.890               0.542               59.36            20.6474   
4  39701.585               0.542               59.36            21.3810   

   Collection  Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  \
0       48000         138.7               7.825                8.095   
1       43200         152.4               7.505                7.650   
2       69400         134.6               7.485                7.570   
3       66800         119.3               6.895                7.035   
4       72400         127.7               6.920                7.070   

   Director_rating  Producer_rating  Twitter_hastags  Avg_age_actors  \
0            7.910            7.995         223.8400              23   
1            7.440            7.470         243.4560              42   
2            7.495            7.515         923.9712              38   
3            6.920            7.020         225.3440              45   
4            6.815            7.070         225.7920              55   

   Num_multiplex  3D_available_YES  Genre_Action  Genre_Comedy  \
0            494                 1             0             0   
1            462                 0             0             0   
2            458                 0             0             1   
3            472                 1             0             0   
4            395                 0             0             0   

   Genre_Thriller  Genre_Drama  MPAA_film_rating_PG  
0               1            0                    1  
1               0            1                    1  
2               0            0                    1  
3               0            1                    1  
4               0            1                    1

In [265]:
y.head()

0    0
1    1
2    0
3    0
4    0
Name: Start_Tech_Oscar, dtype: int64

In [266]:
clrs_lrs=LogisticRegression()

In [267]:
clrs_lrs.fit(X,y)

LogisticRegression()

In [268]:
clrs_lrs.coef_

array([[ 1.57131207e-04, -1.47976356e-05, -2.17982247e-03,
        -7.22100814e-04, -5.54253784e-05, -9.49744108e-03,
         2.72022927e-04,  3.01898767e-04,  2.79998910e-04,
         3.23204321e-04, -5.66216224e-03, -3.85797066e-03,
        -5.58917960e-05, -1.94888238e-04, -3.76773197e-05,
        -1.07966922e-04,  2.44874161e-04, -1.32801422e-04,
        -3.35715022e-05]])

In [269]:
clrs_lrs.intercept_

array([-3.35717664e-05])

In [270]:
import statsmodels.api as sn

In [271]:
x_const=sn.add_constant(X)

In [272]:
x_const.head()

Budget  Multiplex coverage  Production expense  Marketing expense  \
0  36524.125               0.462               59.62            20.1264   
1  35668.655               0.531               69.14            20.5462   
2  39912.675               0.531               69.14            20.5458   
3  38873.890               0.542               59.36            20.6474   
4  39701.585               0.542               59.36            21.3810   

   Collection  Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  \
0       48000         138.7               7.825                8.095   
1       43200         152.4               7.505                7.650   
2       69400         134.6               7.485                7.570   
3       66800         119.3               6.895                7.035   
4       72400         127.7               6.920                7.070   

   Director_rating  Producer_rating  Twitter_hastags  Avg_age_actors  \
0            7.910            7.995         223.8400              23   
1            7.440            7.470         243.4560              42   
2            7.495            7.515         923.9712              38   
3            6.920            7.020         225.3440              45   
4            6.815            7.070         225.7920              55   

   Num_multiplex  3D_available_YES  Genre_Action  Genre_Comedy  \
0            494                 1             0             0   
1            462                 0             0             0   
2            458                 0             0             1   
3            472                 1             0             0   
4            395                 0             0             0   

   Genre_Thriller  Genre_Drama  MPAA_film_rating_PG  
0               1            0                    1  
1               0            1                    1  
2               0            0                    1  
3               0            1                    1  
4               0            1                    1

In [273]:
import statsmodels.discrete.discrete_model as sm

In [274]:
logit=sm.Logit(y,x_const).fit()

Optimization terminated successfully.
         Current function value: 0.618528
         Iterations 7


In [275]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:       Start_Tech_Oscar   No. Observations:                  506
Model:                          Logit   Df Residuals:                      488
Method:                           MLE   Df Model:                           17
Date:                Thu, 07 Mar 2024   Pseudo R-squ.:                  0.1023
Time:                        11:52:10   Log-Likelihood:                -312.98
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 1.273e-08
=======================================================================================
                          coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------
Budget                  0.0002   4.57e-05      4.870      0.000       0.000       0.000
Multiplex coverage      4.6754      2.474      1.890      0.059      -0.173       9.524
Production expense     -0.0096      0.012     -0.768      0.443      -0.034       0.015
Marketing expense      -0.0011      0.001     -1.731      0.083      -0.002       0.000
Collection          -7.236e-05    1.2e-05     -6.006      0.000    -9.6e-05   -4.87e-05
Movie_length           -0.0155      0.006     -2.635      0.008      -0.027      -0.004
Lead_ Actor_Rating     -2.3893      1.622     -1.473      0.141      -5.567       0.789
Lead_Actress_rating     3.1161      1.732      1.800      0.072      -0.278       6.510
Director_rating        -1.8212      1.683     -1.082      0.279      -5.119       1.477
Producer_rating         1.7346      0.918      1.890      0.059      -0.064       3.533
Twitter_hastags        -0.0042      0.002     -1.791      0.073      -0.009       0.000
Avg_age_actors         -0.0021      0.008     -0.266      0.790      -0.017       0.013
Num_multiplex           0.0020      0.002      0.892      0.372      -0.002       0.006
3D_available_YES       -0.2842      0.198     -1.435      0.151      -0.672       0.104
Genre_Action           -1.9909   1.21e+07  -1.65e-07      1.000   -2.37e+07    2.37e+07
Genre_Comedy           -1.9821   1.21e+07  -1.64e-07      1.000   -2.37e+07    2.37e+07
Genre_Thriller         -1.6765   1.21e+07  -1.39e-07      1.000   -2.37e+07    2.37e+07
Genre_Drama            -2.0087   1.21e+07  -1.66e-07      1.000   -2.37e+07    2.37e+07
MPAA_film_rating_PG    -7.6582   1.21e+07  -6.34e-07      1.000   -2.37e+07    2.37e+07
=======================================================================================
"""

In [276]:
clrs_lrs.predict_proba(X)


array([[0.43968088, 0.56031912],
       [0.49009636, 0.50990364],
       [0.98803945, 0.01196055],
       ...,
       [0.45805531, 0.54194469],
       [0.5415111 , 0.4584889 ],
       [0.46067255, 0.53932745]])

In [277]:
y_pred=clrs_lrs.predict(X)

In [278]:
y_pred

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,

In [279]:
y_pred_03=(clrs_lrs.predict_proba(X)[:1]>=0.3).astype(bool)

In [280]:
from sklearn.metrics import confusion_matrix

In [281]:
confusion_matrix(y,y_pred)

array([[186,  90],
       [119, 111]], dtype=int64)

In [282]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [283]:
clf_lda=LinearDiscriminantAnalysis()

In [284]:
clf_lda.fit(X,y)

LinearDiscriminantAnalysis()

In [285]:
y_pred_lda=clf_lda.predict(X)

In [286]:
y_pred_lda

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,

In [287]:
confusion_matrix(y,y_pred_lda)

array([[198,  78],
       [100, 130]], dtype=int64)