In [1]:
import numpy

In [2]:
x=numpy.array([100,200,300])

In [3]:
x

array([100, 200, 300])

In [4]:
print(x)

[100 200 300]


In [5]:
import numpy as np


In [6]:
y=np.array([300,400,500])

In [7]:
y

array([300, 400, 500])

In [8]:
print(y)

[300 400 500]


In [12]:
print(np.__version__)

1.21.6
